### ISSUE TITLE
db_autopwn error

### ISSUE THREAD

**Issue by shuvobwas** [hahwul/metasploit-autopwn#5]
msf6 > db_autopwn -p -t -PI 22
[-] The db_autopwn command is DEPRECATED
[-] See [Six Ways to Automate Metasploit | Rapid7 Blog](http://r-7.co/xY65Zr) instead
[-] Error while running command db_autopwn: undefined method `new’ for nil:NilClass

Call stack:
/usr/share/metasploit-framework/plugins/db_autopwn.rb:177:in block (2 levels) in cmd_db_autopwn' /usr/share/metasploit-framework/lib/msf/core/module_set.rb:232:in block in each_module_list’
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:208:in each' /usr/share/metasploit-framework/lib/msf/core/module_set.rb:208:in each_module_list’
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:74:in each_module' /usr/share/metasploit-framework/plugins/db_autopwn.rb:176:in block in cmd_db_autopwn’
/usr/share/metasploit-framework/plugins/db_autopwn.rb:175:in each' /usr/share/metasploit-framework/plugins/db_autopwn.rb:175:in cmd_db_autopwn’
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in run_command' /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in block in run_single’
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in each' /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in run_single’
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:165:in block in run' /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:309:in block in with_history_manager_context’
/usr/share/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:35:in with_context' /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:306:in with_history_manager_context’
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:133:in run' /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in start’
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in start' /usr/bin/msfconsole:23:in ’
msf6 > Call stack:

**Comment by mephistolist** [comment]
I'm getting the same error:

msf > db_autopwn -p -R great -e -q 127.0.0.1
[-] Error while running command db_autopwn: undefined method '[]' for nil

Call stack:
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:132:in 'Rex'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:167'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:582:in 'Rex'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:531:in 'blo'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:525:in 'Arr'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:525:in 'Rex'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:165:in 'block in Rex::'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:309:in 'block in Rex::'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell/history_manager.rb:35:in '
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:306:in 'Rex::Ui::Text:'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:133:in 'Rex::Ui::Text:'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in '
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in '<main>'
/opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/winrm-2.3.9/lib/winrm/psrp/fragms
/opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/winrm-2.3.9/lib/winrm/psrp/messas
